server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**

        - id: producto-service
          uri: http://localhost:8083
          predicates:
            - Path=/productos/**

        - id: producto-service-categorias
          uri: http://localhost:8083
          predicates:
            - Path=/categorias/**


        - id: ecommerce-service
          uri: http://localhost:8000
          predicates:
            - Path=/ecommerce/**


        - id: ecommerce-service
          uri: http://localhost:8000
          predicates:
            - Path=/ecommerce/accounts/register/**


        - id: ecommerce-service
          uri: http://localhost:8000
          predicates:
            - Path=/ecommerce/chatbot/**


        - id: ecommerce-service
          uri: http://localhost:8000
          predicates:
            - Path=/ecommerce/cart/**


        - id: ecommerce-service
          uri: http://localhost:8000
          predicates:
            - Path=/ecommerce/pedidos/**


        - id: ecommerce-service
          uri: http://localhost:8000
          predicates:
            - Path=/ecommerce/admin/**



